"""
r_script_builder.py — Deterministic R script generator.

The agent's planner decides *what* to map; this module decides *how* to
express that decision as valid sdtm.oak R code.

Key design choice: R code generation is deterministic here, not inside the LLM.
The LLM provides a structured mapping plan (JSON); this module turns it into R.
That means R syntax bugs are reproducible and fixable — not random LLM hallucinations.
"""

from __future__ import annotations

from typing import Any


# ══════════════════════════════════════════════════════════════════════════════
# Public entry point
# ══════════════════════════════════════════════════════════════════════════════

def build_r_script(
    mapping_plan   : dict[str, Any],
    raw_csv        : str,
    ct_csv         : str,
    output_csv     : str,
    study_id       : str = "CDISCPILOT01",
) -> str:
    """
    Given a validated mapping plan (see schema below), return a complete R script.

    mapping_plan schema
    ───────────────────
    {
      "pat_var"     : "PATNUM",          # subject-ID column in raw data
      "date_col"    : "VSDAT",           # date column
      "visit_col"   : "VISIT",           # visit label column
      "visitnum_col": "VISITNUM",        # (optional) numeric visit col
      "position_col": "SUBPOS",          # body position column
      "tests": [
        {
          "testcd"       : "TEMP",
          "testname"     : "Temperature",
          "raw_result_col": "IT.TEMP",
          "raw_unit_col" : null,          # or column name
          "fixed_unit"   : "F",          # used when no unit column
          "loc_col"      : "IT.TEMP_LOC",# (optional)
          "vstestcd_clst": "C66741",
          "vstest_clst"  : "C67153",
          "vsorresu_clst": "C66770",
          "vsstresu_clst": "C66770",
          "vsloc_clst"   : "C74456",
          "vspos_clst"   : "C71148",
          "std_unit"     : "C",           # VSSTRESU value
          "conversion"   : "celsius"      # one of: celsius | mmhg | bpm | none
        },
        ...
      ]
    }
    """
    lines: list[str] = []

    # ── Header ─────────────────────────────────────────────────────────────────
    lines += [
        "# AUTO-GENERATED by sdtm-oak-agent — do not edit by hand",
        "# Generated mapping plan applied via sdtm.oak",
        "",
        "suppressPackageStartupMessages({",
        "  library(sdtm.oak)",
        "  library(dplyr)",
        "})",
        "",
    ]

    # ── Load data ──────────────────────────────────────────────────────────────
    raw_csv_r  = raw_csv.replace("\\", "/")
    ct_csv_r   = ct_csv.replace("\\", "/")
    out_csv_r  = output_csv.replace("\\", "/")

    pat_var    = mapping_plan["pat_var"]
    date_col   = mapping_plan.get("date_col", "VSDAT")
    visit_col  = mapping_plan.get("visit_col", "VISIT")
    visitnum_col = mapping_plan.get("visitnum_col")
    position_col = mapping_plan.get("position_col")

    lines += [
        f'raw_vs   <- read.csv("{raw_csv_r}", stringsAsFactors = FALSE)',
        f'study_ct <- read.csv("{ct_csv_r}",  stringsAsFactors = FALSE)',
        "",
        "# Normalise CT column names (handles any capitalisation variant)",
        "names(study_ct) <- tolower(trimws(names(study_ct)))",
        "",
        "# sdtm.oak expects: codelist_code, codelist_name, term_value, collected_value",
        'if (!("codelist_code" %in% names(study_ct))) {',
        '  stop("CT CSV missing required columns")',
        "}",
        "",
    ]

    # ── Lineage IDs ────────────────────────────────────────────────────────────
    lines += [
        "# Add lineage tracking variables (required by sdtm.oak)",
        f'raw_vs <- generate_oak_id_vars(raw_vs, pat_var = "{pat_var}", raw_src = "vs_raw")',
        "",
    ]

    # ── Per-test mapping blocks ────────────────────────────────────────────────
    test_df_names: list[str] = []

    for test in mapping_plan["tests"]:
        testcd        = test["testcd"]
        testname      = test["testname"]
        raw_result_col = test["raw_result_col"]
        raw_unit_col  = test.get("raw_unit_col")
        fixed_unit    = test.get("fixed_unit", "")
        loc_col       = test.get("loc_col")
        std_unit      = test.get("std_unit", "")
        conversion    = test.get("conversion", "none")

        vstestcd_clst = test.get("vstestcd_clst", "C66741")
        vstest_clst   = test.get("vstest_clst",   "C67153")
        vsorresu_clst = test.get("vsorresu_clst",  "C66770")
        vsstresu_clst = test.get("vsstresu_clst",  "C66770")
        vsloc_clst    = test.get("vsloc_clst",     "C74456")
        vspos_clst    = test.get("vspos_clst",     "C71148")

        df_name = f"vs_{testcd.lower()}"
        test_df_names.append(df_name)

        lines += [
            f"# ── {testcd}: {testname} ────────────────────────────────────────────────────",
            f"{df_name} <- raw_vs |>",
        ]

        # 1) hardcode VSTESTCD (CT-validated)
        lines.append(
            f'  hardcode_ct(raw_var = "{raw_result_col}", tgt_var = "VSTESTCD",\n'
            f'               tgt_val = "{testcd}", ct_spec = study_ct,\n'
            f'               ct_clst = "{vstestcd_clst}", id_vars = oak_id_vars()) |>'
        )

        # 2) filter to rows where VSTESTCD was successfully assigned
        lines.append(
            '  condition_add(condition = !is.na(VSTESTCD)) |>'
        )

        # 3) hardcode VSTEST (CT-validated)
        lines.append(
            f'  hardcode_ct(raw_var = "{raw_result_col}", tgt_var = "VSTEST",\n'
            f'               tgt_val = "{testname}", ct_spec = study_ct,\n'
            f'               ct_clst = "{vstest_clst}", id_vars = oak_id_vars()) |>'
        )

        # 4) original result (copy as-is)
        lines.append(
            f'  assign_no_ct(raw_var = "{raw_result_col}", tgt_var = "VSORRES",\n'
            f'                id_vars = oak_id_vars()) |>'
        )

        # 5) original unit
        if raw_unit_col:
            lines.append(
                f'  assign_ct(raw_var = "{raw_unit_col}", tgt_var = "VSORRESU",\n'
                f'             ct_spec = study_ct, ct_clst = "{vsorresu_clst}",\n'
                f'             id_vars = oak_id_vars()) |>'
            )
        elif fixed_unit:
            lines.append(
                f'  hardcode_ct(raw_var = "{raw_result_col}", tgt_var = "VSORRESU",\n'
                f'               tgt_val = "{fixed_unit}", ct_spec = study_ct,\n'
                f'               ct_clst = "{vsorresu_clst}", id_vars = oak_id_vars()) |>'
            )

        # 6) anatomical location (optional)
        if loc_col:
            lines.append(
                f'  assign_ct(raw_var = "{loc_col}", tgt_var = "VSLOC",\n'
                f'             ct_spec = study_ct, ct_clst = "{vsloc_clst}",\n'
                f'             id_vars = oak_id_vars()) |>'
            )

        # 7) body position (shared across tests — comes from mapping_plan level)
        if position_col:
            lines.append(
                f'  assign_ct(raw_var = "{position_col}", tgt_var = "VSPOS",\n'
                f'             ct_spec = study_ct, ct_clst = "{vspos_clst}",\n'
                f'             id_vars = oak_id_vars()) |>'
            )

        # 8) DOMAIN hardcode (no CT needed)
        lines.append(
            '  hardcode_no_ct(raw_var = NULL, tgt_var = "DOMAIN",\n'
            '                  tgt_val = "VS",  id_vars = oak_id_vars()) |>'
        )

        # 9) visit date
        lines.append(
            f'  assign_no_ct(raw_var = "{date_col}", tgt_var = "VSDTC",\n'
            f'                id_vars = oak_id_vars()) |>'
        )

        # 10) visit label
        lines.append(
            f'  assign_no_ct(raw_var = "{visit_col}", tgt_var = "VISIT",\n'
            f'                id_vars = oak_id_vars())'
        )

        # Post-pipe: add derived/standardised columns
        lines += [
            "",
            f"# Standardised result for {testcd}",
            f"{df_name} <- {df_name} |>",
        ]

        if conversion == "celsius":
            lines.append(
                f'  mutate(\n'
                f'    VSSTRESC = as.character(round((as.numeric(VSORRES) - 32) * 5/9, 2)),\n'
                f'    VSSTRESN = round((as.numeric(VSORRES) - 32) * 5/9, 2),\n'
                f'    VSSTRESU = "{std_unit}"\n'
                f'  )'
            )
        else:
            # For BP, pulse, etc. original == standardised
            lines.append(
                f'  mutate(\n'
                f'    VSSTRESC = as.character(as.numeric(VSORRES)),\n'
                f'    VSSTRESN = as.numeric(VSORRES),\n'
                f'    VSSTRESU = "{std_unit}"\n'
                f'  )'
            )

        # VISITNUM (optional)
        if visitnum_col:
            lines += [
                f"",
                f"# Add numeric visit number for {testcd}",
                f"{df_name}${{'VISITNUM'}} <- as.numeric({df_name}${{'VISITNUM'}})",
                f"if (!('VISITNUM' %in% names({df_name}))) {{",
                f"  {df_name}$VISITNUM <- NA_real_",
                f"}}",
            ]

        lines.append("")

    # ── Stack all test blocks ──────────────────────────────────────────────────
    bind_args = ",\n  ".join(test_df_names)
    lines += [
        "# ── Stack all test datasets ──────────────────────────────────────────────────",
        f"vs_sdtm <- bind_rows(",
        f"  {bind_args}",
        ")",
        "",
    ]

    # ── Add STUDYID + USUBJID ──────────────────────────────────────────────────
    lines += [
        "# STUDYID and USUBJID",
        f'vs_sdtm$STUDYID <- "{study_id}"',
        f'vs_sdtm$USUBJID <- paste0("{study_id}-", vs_sdtm${pat_var})',
        "",
    ]

    # ── Reorder to SDTM-preferred column order ─────────────────────────────────
    lines += [
        "# Reorder columns to SDTM presentation order",
        "preferred_cols <- c(",
        '  "STUDYID", "DOMAIN", "USUBJID",',
        '  "VSTESTCD", "VSTEST",',
        '  "VSORRES", "VSORRESU",',
        '  "VSSTRESC", "VSSTRESN", "VSSTRESU",',
        '  "VSPOS", "VSLOC",',
        '  "VISITNUM", "VISIT", "VSDTC"',
        ")",
        "present_cols <- intersect(preferred_cols, names(vs_sdtm))",
        "extra_cols   <- setdiff(names(vs_sdtm), present_cols)",
        "vs_sdtm      <- vs_sdtm[, c(present_cols, extra_cols)]",
        "",
    ]

    # ── Write output ────────────────────────────────────────────────────────────
    lines += [
        "# Write output",
        f'write.csv(vs_sdtm, "{out_csv_r}", row.names = FALSE)',
        f'cat("SUCCESS: wrote", nrow(vs_sdtm), "rows to {out_csv_r}\\n")',
    ]

    return "\n".join(lines)
