import streamlit as st
import pandas as pd
from agent.graph import app_graph
from agent.tools import read_csv_metadata
import os

st.set_page_config(page_title="AI-LENS SDTM Agent", layout="wide")
st.title("🧪 Clinical SDTM Mapping Agent")

# Ensure output directory exists for the agent
if not os.path.exists("output"):
    os.makedirs("output")

col1, col2 = st.columns(2)

with col1:
    st.header("Inputs")
    raw_file = st.file_uploader("Upload raw VS CSV", type="csv")
    ct_file = st.file_uploader("Upload Study CT CSV", type="csv")

if st.button("Start Agentic Mapping") and raw_file and ct_file:
    # PASS THE FILE OBJECT DIRECTLY
    raw_meta = read_csv_metadata(raw_file)
    ct_meta = read_csv_metadata(ct_file)
    
    initial_state = {
        "raw_data_summary": raw_meta,
        "ct_data_summary": ct_meta,
        "plan": "",
        "r_script": "",
        "validation_results": "",
        "status": "planning",
        "errors": []
    }
    
    with st.status("Agent is working...") as status:
        # Stream the graph execution[cite: 4, 8]
        final_state = initial_state.copy()

        for output in app_graph.stream(initial_state):
            for key, value in output.items():
                final_state.update(value)
                st.write(f"Node **{key}** finished.")
        status.update(label="Mapping Complete!", state="complete")

    st.header("Results")
    # Display the final generated R code from the graph output
    if 'r_script' in final_state:
        st.code(final_state['r_script'], language='r')
    else:
        st.error("R script not generated by agent")

    st.subheader("Validation Results")
    if 'validation_results' in final_state:
        st.write(final_state['validation_results'])
    else:
        st.warning("No validation results found")
    
    if os.path.exists("output/vs.csv"):
        st.success("SDTM Dataset generated successfully!")
        st.dataframe(pd.read_csv("output/vs.csv"))